spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/onlineShop
    username: root
    password: '0209'
  main:
    web-application-type: servlet
  jpa:
    generate-ddl: true
    show-sql: true
server:
  port: 8080

